# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NUnit Tests and Deploy Allure Reports

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4.0.0
      with:
        name: allure-results
        path: .\bin\Debug\net8.0\allure-results
        if-no-files-found: error
        retention-days: 20
    
    - name: Clean up gh-pages branch (optional)
      run: |
        git checkout -f gh-pages
        git rm -rf .  

