
name: NUnit Tests and Deploy Allure Reports

on:
  push:
    branches-ignore:
      - '!main'

jobs:
    autotests:
        name: Run tests and generate Allure Report
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
  
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: |
                    8.0.x

            - name: Restore NuGet packages
              run: dotnet restore

            - name: Build solution
              run: dotnet build --no-restore

            - name: Test solution
              run: dotnet test 
              continue-on-error: true

            - name: Get Allure history
              uses: actions/checkout@v4
              if: always()
              continue-on-error: true
              with:
                ref: gh-pages
                path: gh-pages

            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@v1.7
              if: always()
              with:
                allure_results: allure-results
                allure_history: allure-history

            - name: Deploy report to GitHub Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: allure-history
                publish_branch: gh-pages
